-- Create banners table for promotional slides
CREATE TABLE IF NOT EXISTS banners (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  image_url TEXT NOT NULL,
  link_url TEXT,
  display_order INTEGER DEFAULT 0,
  start_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  end_at TIMESTAMP WITH TIME ZONE,
  slide_duration INTEGER DEFAULT 5000, -- slide duration in ms
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable Realtime for banners
ALTER PUBLICATION supabase_realtime ADD TABLE banners;
